server:
  port: 8082

spring:
  application:
    name: analytics-service

currency-service:
  url: ${CURRENCY_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      jvm: false
      process: false
      system: false
      tomcat: false
      logback: false
      executor: false
      spring.security: false
      disk: false
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.example.analyticsservice: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
